nmckinney_dev:
  outputs:
    dev:
      dataset: stripe
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: /Users/nathanmckinney/Desktop/Github/secret/keyfile.json
      location: US
      method: service-account
      priority: interactive
      project: 'cloud-warehouse-389415'
      threads: 1
      type: bigquery
  target: dev
