version: 2

sources:
  - name: nmckinney_dev
    database: cloud-warehouse-389415
    schema: nmckinney_dev
    tables:
      - name: polygon_stock_data

models:
  - name: polygon_stock_data
    description: test_description




  